export const project = [
  {
    id: 1,
    site: 'https://snrtn.github.io/LandingPage/',
    img: 'https://ifh.cc/g/marHiQ.jpg',
    title: 'Booki',
    desc1: 'Projet Openclassrooms',
    desc2: 'Transformation d’une maquette en une page HTML&CSS',
    desc3: 'Les versions desktop et mobile',
    code: 'https://github.com/snrtn/LandingPage',
  },
  {
    id: 2,
    site: 'https://snrtn.github.io/portfoliodetype/',
    img: 'https://ifh.cc/g/hK9fjN.jpg',
    title: 'Portfolio',
    desc1: 'Projet personnel',
    desc2: 'React',
    desc3: 'Les versions desktop et mobile',
    code: 'https://github.com/snrtn/typereact',
  },
  {
    id: 3,
    site: 'https://snrtn.github.io/portfolioract/#/',
    img: 'https://ifh.cc/g/Y45tiQ.jpg',
    title: 'Portfolio',
    desc1: 'Projet personnel',
    desc2: 'React',
    desc3: 'Le version desktop',
    code: 'https://github.com/snrtn/presentation',
  },
];
