export const exp = [
  {
    title: 'Opérateur de contrôle numérique, Machine-outil équipe',
    subtitle: 'Séoul (Corée du Sud / Dongdaemun-gu) – formation au sein de l’école',
    data: 'Période : 2010-2012',
    dect: 'Maintenance de la machine',
    decta: 'Fabrication de pièces automobile/moto',
    dectb: '',
    img: 'https://images.pexels.com/photos/48799/drill-milling-milling-machine-drilling-48799.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260',
  },
  {
    title: 'Technicien aéronautique, Armée de l’air',
    subtitle: 'Wonju (Corée du Sud / 8th Fighter Wing) – Service militaire',
    data: 'Période : 2013-2015',
    dect: 'En charge de la maintenance technique des avions de chasse',
    decta: 'En charge de l’inventaire, du nettoyage et de la distribution des armes',
    dectb: '',
    img: 'https://images.pexels.com/photos/733254/pexels-photo-733254.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260',
  },
  {
    title: 'Garde sécurité, POSCO',
    subtitle: 'Séoul (Corée du Sud / Gannam-gu) – Entreprise dans la production d’acier',
    data: 'Période : 2016-2018',
    dect: 'En charge de la protection du PDG',
    decta: '',
    dectb: '',
    img: 'https://www.ild-security.com/wp-content/uploads/2018/01/20.jpg',
  },
  {
    title: 'Employé de service, E. Leclerc',
    subtitle: 'Montévrain',
    data: 'Période : 2019-2020',
    dect: 'Nettoyage des rayons',
    decta: 'Mettre les aliments et produits en rayon',
    dectb: 'Organisation du magasin',
    img: 'https://images.pexels.com/photos/264636/pexels-photo-264636.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260',
  },
];
